# Generated by Django 2.2.3 on 2019-07-12 15:47

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('history', django.contrib.gis.db.models.fields.MultiPointField(blank=True, srid=4326)),
                ('num_posts', models.PositiveIntegerField(default=0)),
                ('num_comments', models.PositiveIntegerField(default=0)),
                ('num_reports', models.PositiveIntegerField(default=0)),
                ('num_violations', models.PositiveIntegerField(default=0)),
                ('ban_level', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
            ],
        ),
    ]
